name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
    
env:
  IMAGE_NAME: cfautoupdater

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
        
    - name: Build and Push Versioned Docker Image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        flavor:
          latest:auto
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
